# -*- coding: utf-8 -*-
"""data_punctuation_analysiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PW1XSROQne9KTkdltiO8F4hzUi0C3VLk
"""

import pandas as pd
import re
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

SAVE_PATH = "/content/drive/MyDrive/shared_ml_workspace/data/dataset_lazy.csv"
CHUNK_SIZE = 10_000

total_sentences = 0
min_len = float("inf")
max_len = 0
sum_len = 0

for chunk in pd.read_csv(SAVE_PATH, chunksize=CHUNK_SIZE):
    lens = chunk["input"].apply(len)

    total_sentences += len(chunk)
    min_len = min(min_len, lens.min())
    max_len = max(max_len, lens.max())
    sum_len += lens.sum()

avg_len = sum_len / total_sentences

print("Number of sentences:", total_sentences)
print("Min sentence length:", min_len)
print("Max sentence length:", max_len)
print("Average sentence length:", avg_len)

LABELS = {
    "O": 0,
    ".": 1,
    "،": 2,
    "؟": 3,
    "!": 4,
    "؛": 5,
    ":": 6
}

id2label = {v: k for k, v in LABELS.items()}
label_counts = Counter()

for chunk in pd.read_csv(SAVE_PATH, chunksize=CHUNK_SIZE):
    for seq in chunk["output"]:
        for lbl in seq:
            if lbl != 0:
                label_counts[lbl] += 1

for k, v in label_counts.items():
    print(f"Number of ({id2label[k]}) detected:", v)

label_names = {
    1:".",
    2:"،",
    3:"؟",
    4:"!",
    5:"؛",
    6:":"
}

labels = [label_names[k] for k in label_counts.keys()]
values = list(label_counts.values())

plt.figure(figsize=(8,8))
patches, _ = plt.pie(
    values,
    labels=labels,
    startangle=90,
    pctdistance=1.15
)

percentages = [
    f"{l}: {v/sum(values)*100:.1f}%"
    for l, v in zip(labels, values)
]

plt.legend(
    patches,
    percentages,
    title="Punctuation %",
    loc="center left",
    bbox_to_anchor=(1, 0.5)
)

plt.title("Punctuation Distribution (excluding O)")
plt.tight_layout()
plt.show()

length_samples = []

for chunk in pd.read_csv(SAVE_PATH, chunksize=CHUNK_SIZE):
    length_samples.extend(chunk["input"].apply(len).sample(frac=0.1))

plt.figure(figsize=(8,4))
sns.boxplot(x=length_samples)
plt.title("Sentence Length Boxplot (sampled)")
plt.xlabel("Sentence Length")
plt.show()